//! GTFS-RT protobuf decode using prost-generated types.
//!
//! # Prost + proto2 quirks
//!
//! The official GTFS-realtime schema is **proto2**. With prost:
//!
//! - **Required** scalar/message fields become plain non-`Option` fields (e.g.
//!   `TripUpdate.trip`, `Position.latitude` / `longitude`). They still decode
//!   as defaults (0 / empty) if the wire message omitted them — we must not
//!   assume presence and should skip invalid entities (empty `trip_id`,
//!   0,0 position).
//! - **Optional** scalars/messages become `Option<T>` and may be `None`.
//! - **Enum** fields: use the generated `*_or_default` / accessor methods
//!   (e.g. `schedule_relationship()`) rather than unwrapping raw integers.
//! - **`is_deleted`** on feed entities is optional; treat missing as false.
//! - **Full dataset** vs differential: when `header.incrementality` is
//!   `FULL_DATASET` (default in many feeds), clear the relevant map before
//!   applying entities.
//!
//! # Trip key strategy
//!
//! Each trip is stored as `feed_id:trip_id`. When `start_date` is present and
//! non-empty, the same [`TripRt`] is also inserted as
//! `feed_id:trip_id@YYYYMMDD` (see [`FeedRtState::insert_trip`]).

use chrono::{TimeZone, Utc};
use tracing::warn;

use super::overlay::{AlertRt, FeedRtState, StopTimeRt, TripRt, VehiclePos};

// Generated by build.rs from proto/gtfs-realtime.proto
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/transit_realtime.rs"));
}

use pb::feed_header::Incrementality;
use pb::trip_descriptor::ScheduleRelationship as TripRel;
use pb::trip_update::stop_time_update::ScheduleRelationship as StuRel;
use pb::FeedMessage;

pub fn decode_feed_message(bytes: &[u8]) -> Result<FeedMessage, prost::DecodeError> {
    use prost::Message;
    FeedMessage::decode(bytes)
}

pub fn apply_trip_updates(feed_id: &str, bytes: &[u8], state: &mut FeedRtState) {
    let msg = match decode_feed_message(bytes) {
        Ok(m) => m,
        Err(e) => {
            warn!(feed_id, error = %e, "failed to decode trip updates");
            return;
        }
    };
    state.trip_updates_fetched_at = Some(Utc::now());
    if let Some(h) = msg.header.timestamp {
        state.header_timestamp = Some(h as i64);
    }
    if msg.header.incrementality() == Incrementality::FullDataset {
        state.trips.clear();
    }

    for entity in msg.entity {
        if entity.is_deleted.unwrap_or(false) {
            // Differential delete: remove by entity trip if we can.
            // Without trip payload we skip (id alone is not our trip map key).
            continue;
        }
        let Some(tu) = entity.trip_update else {
            continue;
        };
        // trip is required message in proto2 → plain struct in prost (always present after decode)
        let trip = tu.trip;
        let raw_trip_id = trip
            .trip_id
            .clone()
            .filter(|s| !s.is_empty())
            .unwrap_or_default();

        // start_date is optional string YYYYMMDD
        let start_date = trip.start_date.clone().filter(|s| !s.is_empty());
        let start_time = trip.start_time.clone().filter(|s| !s.is_empty());
        let route_id = trip
            .route_id
            .as_ref()
            .filter(|s| !s.is_empty())
            .map(|r| format!("{feed_id}:{r}"));
        let direction_id = trip.direction_id;

        // Incomplete entities (no trip_id) need at least route_id to be useful.
        if raw_trip_id.is_empty() && route_id.is_none() {
            continue;
        }

        // schedule_relationship defaults to SCHEDULED when unset
        let canceled = matches!(trip.schedule_relationship(), TripRel::Canceled);

        let mut stop_updates = std::collections::HashMap::new();
        for stu in tu.stop_time_update {
            // stop_sequence optional; 0 is valid but rare — still accept
            let seq = stu.stop_sequence.unwrap_or(0) as u16;
            let stop_id = stu
                .stop_id
                .as_ref()
                .filter(|s| !s.is_empty())
                .map(|s| format!("{feed_id}:{s}"));
            let arrival_delay = stu.arrival.as_ref().and_then(|a| a.delay);
            let departure_delay = stu.departure.as_ref().and_then(|d| d.delay);
            let arrival_time = stu.arrival.as_ref().and_then(|a| a.time);
            let departure_time = stu.departure.as_ref().and_then(|d| d.time);
            let skipped = matches!(stu.schedule_relationship(), StuRel::Skipped);
            stop_updates.insert(
                seq,
                StopTimeRt {
                    stop_sequence: seq,
                    stop_id,
                    arrival_delay,
                    departure_delay,
                    arrival_time,
                    departure_time,
                    skipped,
                },
            );
        }

        // Trip-level delay is optional (seconds)
        let delay = tu.delay;

        state.insert_trip(
            feed_id,
            &raw_trip_id,
            TripRt {
                delay,
                canceled,
                start_date,
                route_id,
                direction_id,
                start_time,
                stop_updates,
            },
        );
    }
    // Count undated keys so dual-insert does not inflate the metric
    state.trip_update_count = state
        .trips
        .keys()
        .filter(|k| !k.contains('@'))
        .count();
}

pub fn apply_vehicle_positions(feed_id: &str, bytes: &[u8], state: &mut FeedRtState) {
    let msg = match decode_feed_message(bytes) {
        Ok(m) => m,
        Err(e) => {
            warn!(feed_id, error = %e, "failed to decode vehicle positions");
            return;
        }
    };
    state.vehicles_fetched_at = Some(Utc::now());
    if let Some(h) = msg.header.timestamp {
        state.header_timestamp = Some(h as i64);
    }
    if msg.header.incrementality() == Incrementality::FullDataset {
        state.vehicles.clear();
    }

    for entity in msg.entity {
        if entity.is_deleted.unwrap_or(false) {
            continue;
        }
        let Some(vp) = entity.vehicle else {
            continue;
        };
        let trip_id = vp
            .trip
            .as_ref()
            .and_then(|t| t.trip_id.clone())
            .filter(|s| !s.is_empty())
            .map(|t| format!("{feed_id}:{t}"));
        let Some(pos) = vp.position else {
            continue;
        };
        // latitude/longitude are required floats in proto2 — default 0.0 if missing
        let lat = pos.latitude as f64;
        let lon = pos.longitude as f64;
        if lat == 0.0 && lon == 0.0 {
            continue;
        }
        let updated_at = vp
            .timestamp
            .and_then(|t| Utc.timestamp_opt(t as i64, 0).single())
            .unwrap_or_else(Utc::now);
        let key = trip_id
            .clone()
            .or_else(|| {
                if entity.id.is_empty() {
                    None
                } else {
                    Some(format!("{feed_id}:{}", entity.id))
                }
            })
            .unwrap_or_else(|| format!("{feed_id}:veh"));
        let veh = vp.vehicle.as_ref();
        let label = veh
            .and_then(|v| v.label.clone())
            .filter(|s| !s.is_empty());
        let vehicle_id = veh
            .and_then(|v| v.id.clone())
            .filter(|s| !s.is_empty());
        let license_plate = veh
            .and_then(|v| v.license_plate.clone())
            .filter(|s| !s.is_empty());

        // Only set enum-backed strings when the wire field is present (not default-filled).
        let occupancy = vp.occupancy_status.map(|_| {
            vp.occupancy_status().as_str_name().to_string()
        });
        let current_status = vp.current_status.map(|_| {
            vp.current_status().as_str_name().to_string()
        });
        let congestion = vp.congestion_level.map(|_| {
            vp.congestion_level().as_str_name().to_string()
        });

        // Prefer vehicle-level occupancy_percentage; else average multi-carriage values ≥ 0.
        let occupancy_percentage = vp.occupancy_percentage.or_else(|| {
            let pcts: Vec<u32> = vp
                .multi_carriage_details
                .iter()
                .filter_map(|c| {
                    c.occupancy_percentage.and_then(|p| {
                        if p >= 0 {
                            Some(p as u32)
                        } else {
                            None
                        }
                    })
                })
                .collect();
            if pcts.is_empty() {
                None
            } else {
                let sum: u32 = pcts.iter().sum();
                Some(sum / pcts.len() as u32)
            }
        });

        state.vehicles.insert(
            key,
            VehiclePos {
                trip_id,
                lat,
                lon,
                bearing: pos.bearing.map(|b| b as f64),
                speed: pos.speed.map(|s| s as f64),
                updated_at,
                current_stop_id: vp
                    .stop_id
                    .as_ref()
                    .filter(|s| !s.is_empty())
                    .map(|s| format!("{feed_id}:{s}")),
                label,
                vehicle_id,
                license_plate,
                occupancy,
                current_status,
                current_stop_sequence: vp.current_stop_sequence,
                congestion,
                occupancy_percentage,
            },
        );
    }
    state.vehicle_count = state.vehicles.len();
}

pub fn apply_service_alerts(feed_id: &str, bytes: &[u8], state: &mut FeedRtState) {
    let msg = match decode_feed_message(bytes) {
        Ok(m) => m,
        Err(e) => {
            warn!(feed_id, error = %e, "failed to decode service alerts");
            return;
        }
    };
    state.alerts_fetched_at = Some(Utc::now());
    if let Some(h) = msg.header.timestamp {
        state.header_timestamp = Some(h as i64);
    }
    if msg.header.incrementality() == Incrementality::FullDataset {
        state.alerts.clear();
    }

    for entity in msg.entity {
        if entity.is_deleted.unwrap_or(false) {
            continue;
        }
        let Some(alert) = entity.alert else {
            continue;
        };
        let id = if entity.id.is_empty() {
            format!("{feed_id}:alert:{}", state.alerts.len())
        } else {
            entity.id.clone()
        };
        let header_translations: Vec<(String, String)> = alert
            .header_text
            .as_ref()
            .map(|t| {
                t.translation
                    .iter()
                    .filter(|tr| !tr.text.is_empty())
                    .map(|tr| {
                        (
                            tr.language.clone().unwrap_or_default(),
                            tr.text.clone(),
                        )
                    })
                    .collect()
            })
            .unwrap_or_default();
        let desc_translations: Vec<(String, String)> = alert
            .description_text
            .as_ref()
            .map(|t| {
                t.translation
                    .iter()
                    .filter(|tr| !tr.text.is_empty())
                    .map(|tr| {
                        (
                            tr.language.clone().unwrap_or_default(),
                            tr.text.clone(),
                        )
                    })
                    .collect()
            })
            .unwrap_or_default();
        // Prefer French (not first language — SNCF often ships DE first + HTML).
        let header = crate::rt::alert_text::pick_translation(&header_translations);
        let description = crate::rt::alert_text::pick_translation(&desc_translations);

        let mut informed_stop_ids = Vec::new();
        let mut informed_route_ids = Vec::new();
        let mut informed_trip_ids = Vec::new();
        for ie in &alert.informed_entity {
            if let Some(ref s) = ie.stop_id {
                if !s.is_empty() {
                    informed_stop_ids.push(format!("{feed_id}:{s}"));
                }
            }
            if let Some(ref r) = ie.route_id {
                if !r.is_empty() {
                    informed_route_ids.push(format!("{feed_id}:{r}"));
                }
            }
            if let Some(t) = ie.trip.as_ref().and_then(|tr| tr.trip_id.as_ref()) {
                if !t.is_empty() {
                    informed_trip_ids.push(format!("{feed_id}:{t}"));
                }
            }
        }

        let severity = match alert.severity_level() {
            pb::alert::SeverityLevel::Severe => "SEVERE",
            pb::alert::SeverityLevel::Warning => "WARNING",
            pb::alert::SeverityLevel::Info => "INFO",
            _ => "INFO",
        }
        .to_string();

        let cause = alert
            .cause
            .map(|_| alert.cause().as_str_name().to_string());
        let effect = alert
            .effect
            .map(|_| alert.effect().as_str_name().to_string());
        let url = alert
            .url
            .as_ref()
            .and_then(|t| t.translation.first())
            .map(|tr| tr.text.clone())
            .filter(|s| !s.is_empty());

        // All active_period ranges; keep first as active_start/end for compat.
        #[allow(deprecated)]
        let active_periods: Vec<(Option<i64>, Option<i64>)> = alert
            .active_period
            .iter()
            .map(|tr| (tr.start.map(|s| s as i64), tr.end.map(|e| e as i64)))
            .collect();
        let (active_start, active_end) = active_periods
            .first()
            .copied()
            .unwrap_or((None, None));

        state.alerts.push(AlertRt {
            id: format!("{feed_id}:{id}"),
            header,
            description,
            severity,
            informed_stop_ids,
            informed_route_ids,
            informed_trip_ids,
            cause,
            effect,
            url,
            active_start,
            active_end,
            active_periods,
            header_translations,
        });
    }
    state.alert_count = state.alerts.len();
}

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;

    /// Build a minimal FeedMessage with one trip update using prost encode.
    fn encode_trip_update_feed(
        trip_id: Option<&str>,
        start_date: Option<&str>,
        trip_delay: Option<i32>,
        canceled: bool,
        stop_seq: u32,
        stop_delay: i32,
        skipped: bool,
        route_id: Option<&str>,
        direction_id: Option<u32>,
        start_time: Option<&str>,
    ) -> Vec<u8> {
        use pb::trip_descriptor::ScheduleRelationship as TripSr;
        use pb::trip_update::stop_time_update::ScheduleRelationship as StuSr;
        use pb::trip_update::{StopTimeEvent, StopTimeUpdate};
        use pb::{FeedEntity, FeedHeader, FeedMessage, TripDescriptor, TripUpdate};

        let stu = StopTimeUpdate {
            stop_sequence: Some(stop_seq),
            stop_id: Some("S1".into()),
            arrival: Some(StopTimeEvent {
                delay: Some(stop_delay),
                time: None,
                uncertainty: None,
                scheduled_time: None,
            }),
            departure: None,
            schedule_relationship: Some(if skipped {
                StuSr::Skipped as i32
            } else {
                StuSr::Scheduled as i32
            }),
            stop_time_properties: None,
            departure_occupancy_status: None,
        };

        let trip = TripDescriptor {
            trip_id: trip_id.filter(|s| !s.is_empty()).map(|s| s.into()),
            route_id: route_id.map(|s| s.into()),
            direction_id,
            start_time: start_time.map(|s| s.into()),
            start_date: start_date.map(|s| s.into()),
            schedule_relationship: Some(if canceled {
                TripSr::Canceled as i32
            } else {
                TripSr::Scheduled as i32
            }),
            modified_trip: None,
        };

        let tu = TripUpdate {
            trip,
            vehicle: None,
            stop_time_update: vec![stu],
            timestamp: None,
            delay: trip_delay,
            trip_properties: None,
        };

        let msg = FeedMessage {
            header: FeedHeader {
                gtfs_realtime_version: "2.0".into(),
                incrementality: Some(Incrementality::FullDataset as i32),
                timestamp: Some(1_700_000_000),
                feed_version: None,
            },
            entity: vec![FeedEntity {
                id: "e1".into(),
                is_deleted: None,
                trip_update: Some(tu),
                vehicle: None,
                alert: None,
                shape: None,
                stop: None,
                trip_modifications: None,
            }],
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf).unwrap();
        buf
    }

    #[test]
    fn decode_trip_update_delay_and_dual_key() {
        let bytes = encode_trip_update_feed(
            Some("TRIP42"),
            Some("20240601"),
            Some(30),
            false,
            5,
            180,
            false,
            Some("R99"),
            Some(1),
            Some("12:30:00"),
        );
        let mut state = FeedRtState::new("idf");
        apply_trip_updates("idf", &bytes, &mut state);

        assert!(state.trips.contains_key("idf:TRIP42"));
        assert!(state.trips.contains_key("idf:TRIP42@20240601"));
        assert_eq!(state.trip_update_count, 1);

        let t = state.get_trip("idf:TRIP42").unwrap();
        assert_eq!(t.delay, Some(30));
        assert!(!t.canceled);
        assert_eq!(t.start_date.as_deref(), Some("20240601"));
        assert_eq!(t.route_id.as_deref(), Some("idf:R99"));
        assert_eq!(t.direction_id, Some(1));
        assert_eq!(t.start_time.as_deref(), Some("12:30:00"));
        let stu = t.stop_updates.get(&5).unwrap();
        assert_eq!(stu.arrival_delay, Some(180));
        assert_eq!(stu.stop_id.as_deref(), Some("idf:S1"));
        assert!(!stu.skipped);
    }

    #[test]
    fn decode_canceled_and_skipped() {
        let bytes = encode_trip_update_feed(
            Some("CX1"),
            None,
            None,
            true,
            1,
            0,
            true,
            None,
            None,
            None,
        );
        let mut state = FeedRtState::new("sncf");
        apply_trip_updates("sncf", &bytes, &mut state);
        let t = state.get_trip("sncf:CX1").unwrap();
        assert!(t.canceled);
        assert!(t.stop_updates.get(&1).unwrap().skipped);
        // no start_date → single key only
        assert!(!state.trips.keys().any(|k| k.contains('@')));
    }

    #[test]
    fn decode_incomplete_trip_match_by_route_direction_date() {
        let bytes = encode_trip_update_feed(
            None, // no trip_id
            Some("20240615"),
            Some(45),
            false,
            2,
            90,
            false,
            Some("LINE_A"),
            Some(0),
            Some("09:00:00"),
        );
        let mut state = FeedRtState::new("idf");
        apply_trip_updates("idf", &bytes, &mut state);

        assert!(state.get_trip("idf:LINE_A").is_none());
        let t = state
            .find_trip_by_descriptor("idf:LINE_A", Some(0), Some("20240615"))
            .expect("incomplete entity by route+dir+date");
        assert_eq!(t.delay, Some(45));
        assert_eq!(t.route_id.as_deref(), Some("idf:LINE_A"));
        assert_eq!(t.direction_id, Some(0));
        assert_eq!(t.start_date.as_deref(), Some("20240615"));
        assert_eq!(t.start_time.as_deref(), Some("09:00:00"));

        let mut ov = super::super::overlay::RealtimeOverlay::default();
        ov.feeds.insert("idf".into(), state);
        let matched = ov
            .get_trip_matching(None, Some("idf:LINE_A"), Some(0), Some("20240615"))
            .expect("overlay fallback");
        assert_eq!(matched.delay, Some(45));
    }

    #[test]
    fn empty_bytes_no_panic() {
        let mut state = FeedRtState::new("x");
        apply_trip_updates("x", b"", &mut state);
        apply_vehicle_positions("x", b"not protobuf", &mut state);
        apply_service_alerts("x", b"\x00\x01", &mut state);
        assert!(state.trips.is_empty());
    }

    fn encode_vehicle_position_feed() -> Vec<u8> {
        use pb::vehicle_position::{CongestionLevel, OccupancyStatus, VehicleStopStatus};
        use pb::{
            FeedEntity, FeedHeader, FeedMessage, Position, TripDescriptor, VehicleDescriptor,
            VehiclePosition,
        };

        let vp = VehiclePosition {
            trip: Some(TripDescriptor {
                trip_id: Some("T99".into()),
                route_id: None,
                direction_id: None,
                start_time: None,
                start_date: None,
                schedule_relationship: None,
                modified_trip: None,
            }),
            vehicle: Some(VehicleDescriptor {
                id: Some("bus-7".into()),
                label: Some("Line 12".into()),
                license_plate: Some("AB-123-CD".into()),
                wheelchair_accessible: None,
            }),
            position: Some(Position {
                latitude: 48.85,
                longitude: 2.35,
                bearing: Some(90.0),
                odometer: None,
                speed: Some(8.5),
            }),
            current_stop_sequence: Some(3),
            stop_id: Some("S1".into()),
            current_status: Some(VehicleStopStatus::StoppedAt as i32),
            timestamp: Some(1_700_000_100),
            congestion_level: Some(CongestionLevel::Congestion as i32),
            occupancy_status: Some(OccupancyStatus::ManySeatsAvailable as i32),
            occupancy_percentage: Some(42),
            multi_carriage_details: vec![],
        };

        let msg = FeedMessage {
            header: FeedHeader {
                gtfs_realtime_version: "2.0".into(),
                incrementality: Some(Incrementality::FullDataset as i32),
                timestamp: Some(1_700_000_100),
                feed_version: None,
            },
            entity: vec![FeedEntity {
                id: "v1".into(),
                is_deleted: None,
                trip_update: None,
                vehicle: Some(vp),
                alert: None,
                shape: None,
                stop: None,
                trip_modifications: None,
            }],
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf).unwrap();
        buf
    }

    #[test]
    fn decode_vehicle_occupancy_label_status() {
        let bytes = encode_vehicle_position_feed();
        let mut state = FeedRtState::new("idf");
        apply_vehicle_positions("idf", &bytes, &mut state);

        assert_eq!(state.vehicle_count, 1);
        let v = state.vehicles.get("idf:T99").expect("vehicle by trip key");
        assert_eq!(v.label.as_deref(), Some("Line 12"));
        assert_eq!(v.vehicle_id.as_deref(), Some("bus-7"));
        assert_eq!(v.license_plate.as_deref(), Some("AB-123-CD"));
        assert_eq!(v.occupancy.as_deref(), Some("MANY_SEATS_AVAILABLE"));
        assert_eq!(v.current_status.as_deref(), Some("STOPPED_AT"));
        assert_eq!(v.current_stop_sequence, Some(3));
        assert_eq!(v.congestion.as_deref(), Some("CONGESTION"));
        assert_eq!(v.current_stop_id.as_deref(), Some("idf:S1"));
        assert_eq!(v.occupancy_percentage, Some(42));
        // f32 wire precision for lat/lon
        assert!((v.lat - 48.85).abs() < 1e-4);
        assert!((v.lon - 2.35).abs() < 1e-4);
    }

    fn encode_alert_feed() -> Vec<u8> {
        use pb::alert::{Cause, Effect, SeverityLevel};
        use pb::translated_string::Translation;
        use pb::{
            Alert, EntitySelector, FeedEntity, FeedHeader, FeedMessage, TimeRange,
            TranslatedString,
        };

        #[allow(deprecated)]
        let alert = Alert {
            active_period: vec![
                TimeRange {
                    start: Some(1_700_000_000),
                    end: Some(1_700_086_400),
                },
                TimeRange {
                    start: Some(1_700_172_800),
                    end: Some(1_700_259_200),
                },
            ],
            communication_period: vec![],
            impact_period: vec![],
            informed_entity: vec![EntitySelector {
                agency_id: None,
                route_id: Some("R1".into()),
                route_type: None,
                trip: None,
                stop_id: Some("S1".into()),
                direction_id: None,
            }],
            cause: Some(Cause::Construction as i32),
            effect: Some(Effect::SignificantDelays as i32),
            url: Some(TranslatedString {
                translation: vec![Translation {
                    text: "https://example.com/alert".into(),
                    language: Some("en".into()),
                }],
            }),
            header_text: Some(TranslatedString {
                translation: vec![
                    Translation {
                        text: "Works".into(),
                        language: Some("en".into()),
                    },
                    Translation {
                        text: "Travaux".into(),
                        language: Some("fr".into()),
                    },
                ],
            }),
            description_text: Some(TranslatedString {
                translation: vec![
                    Translation {
                        text: "<p>Bauarbeiten</p>".into(),
                        language: Some("de".into()),
                    },
                    Translation {
                        text: "<p>Travaux sur la ligne</p>".into(),
                        language: Some("fr".into()),
                    },
                ],
            }),
            tts_header_text: None,
            tts_description_text: None,
            severity_level: Some(SeverityLevel::Warning as i32),
            image: None,
            image_alternative_text: None,
            cause_detail: None,
            effect_detail: None,
        };

        let msg = FeedMessage {
            header: FeedHeader {
                gtfs_realtime_version: "2.0".into(),
                incrementality: Some(Incrementality::FullDataset as i32),
                timestamp: Some(1_700_000_000),
                feed_version: None,
            },
            entity: vec![FeedEntity {
                id: "a1".into(),
                is_deleted: None,
                trip_update: None,
                vehicle: None,
                alert: Some(alert),
                shape: None,
                stop: None,
                trip_modifications: None,
            }],
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf).unwrap();
        buf
    }

    #[test]
    fn decode_alert_cause_effect_url_period() {
        let bytes = encode_alert_feed();
        let mut state = FeedRtState::new("sncf");
        apply_service_alerts("sncf", &bytes, &mut state);

        assert_eq!(state.alert_count, 1);
        let a = &state.alerts[0];
        assert_eq!(a.cause.as_deref(), Some("CONSTRUCTION"));
        assert_eq!(a.effect.as_deref(), Some("SIGNIFICANT_DELAYS"));
        assert_eq!(a.url.as_deref(), Some("https://example.com/alert"));
        assert_eq!(a.active_start, Some(1_700_000_000));
        assert_eq!(a.active_end, Some(1_700_086_400));
        assert_eq!(
            a.active_periods,
            vec![
                (Some(1_700_000_000), Some(1_700_086_400)),
                (Some(1_700_172_800), Some(1_700_259_200)),
            ]
        );
        assert_eq!(a.header.as_deref(), Some("Travaux"));
        assert_eq!(a.description.as_deref(), Some("Travaux sur la ligne"));
        assert_eq!(
            a.header_translations,
            vec![
                ("en".into(), "Works".into()),
                ("fr".into(), "Travaux".into()),
            ]
        );
        assert_eq!(a.severity, "WARNING");
        assert_eq!(a.informed_route_ids, vec!["sncf:R1".to_string()]);
        assert_eq!(a.informed_stop_ids, vec!["sncf:S1".to_string()]);
    }
}
